import React from "react";
const BrandList = [
  {
    id: 1,
    brandname: "muji",
    saleperiod: "",
    relatedBrands: ["topten", "h&m", "spao", "eight", "uniqlo", "zara"],
    category: "spa",
    tag: ["SPA", "Basic", "Simple"],
  },
  {
    id: 2,
    brandname: "spao",
    saleperiod: "",
    relatedBrands: ["topten", "h&m", "muji", "eight", "uniqlo", "zara"],
    category: "spa",
    tag: ["SPA", "Basic", "Simple"],
  },
  {
    id: 3,
    brandname: "topten",
    saleperiod: "",
    relatedBrands: ["h&m", "spao", "muji", "eight", "uniqlo", "zara"],
    category: "spa",
    tag: ["SPA", "Basic", "Simple"],
  },
  {
    id: 4,
    brandname: "adidas",
    saleperiod: "",
    relatedBrands: ["nike", "xexymix", "nb", "fila", "north"],
    category: "sports",
    tag: ["Sports", "Casual", "Outdoor"],
  },
  {
    id: 5,
    brandname: "nike",
    saleperiod: "",
    relatedBrands: ["adidas", "xexymix", "nb", "fila", "north"],
    category: "sports",
    tag: ["Sports", "Casual", "Outdoor"],
  },
  {
    id: 6,
    brandname: "beanpole",
    saleperiod: "",
    relatedBrands: ["polo", "tomboy"],
    category: "basic",
    tag: ["Normal", "Classic", "Modern"],
  },
  {
    id: 7,
    brandname: "polo",
    saleperiod: "",
    relatedBrands: ["beanpole", "tomboy"],
    category: "basic",
    tag: ["Normal", "Classic", "Modern"],
  },
  {
    id: 8,
    brandname: "tomboy",
    saleperiod: "",
    relatedBrands: ["polo", "beanpole"],
    category: "basic",
    tag: ["Normal", "Classic", "Modern"],
  },
  {
    id: 9,
    brandname: "kbp",
    saleperiod: "",
    relatedBrands: ["yankee", "ikea"],
    category: "etc",
    tag: ["Unique", "Sensitive", "Fabric"],
  },
  {
    id: 10,
    brandname: "nb",
    saleperiod: "",
    relatedBrands: ["adidas", "nike", "xexymix", "fila", "north"],
    category: "sports",
    tag: ["Sports", "Casual", "Outdoor"],
  },
  {
    id: 11,
    brandname: "h&m",
    saleperiod: "",
    relatedBrands: ["topten", "spao", "muji", "eight", "uniqlo", "zara"],
    category: "spa",
    tag: ["SPA", "Basic", "Simple"],
  },
  {
    id: 12,
    brandname: "xexymix",
    saleperiod: "",
    relatedBrands: ["adidas", "nike", "nb", "fila", "north"],
    category: "sports",
    tag: ["Sports", "Casual", "Outdoor"],
  },
  {
    id: 13,
    brandname: "yankee",
    saleperiod: "",
    relatedBrands: ["yankee", "kbp"],
    category: "etc",
    tag: ["Unique", "Sensible ", "Fragrant"],
  },
  {
    id: 14,
    brandname: "ikea",
    saleperiod: "",
    relatedBrands: ["kbp", "ikea"],
    category: "etc",
    tag: ["Reasonable", "Modern", "Indoor"],
  },
  {
    id: 15,
    brandname: "zara",
    saleperiod: "",
    relatedBrands: ["topten", "h&m", "spao", "muji", "eight", "uniqlo"],
    category: "spa",
    tag: ["SPA", "Basic", "Simple"],
  },
  {
    id: 16,
    brandname: "fila",
    saleperiod: "",
    relatedBrands: ["adidas", "nike", "xexymix", "nb", "north"],
    category: "sports",
    tag: ["Sports", "Casual", "Outdoor"],
  },
  {
    id: 17,
    brandname: "eight",
    saleperiod: "",
    relatedBrands: ["topten", "h&m", "spao", "muji", "eight", "uniqlo"],
    category: "spa",
    tag: ["SPA", "Basic", "Simple"],
  },
  {
    id: 18,
    brandname: "uniqlo",
    saleperiod: "",
    relatedBrands: ["topten", "h&m", "spao", "muji", "eight", "zara"],
    category: "spa",
    tag: ["SPA", "Basic", "Simple"],
  },
  {
    id: 19,
    brandname: "north",
    saleperiod: "",
    relatedBrands: ["adidas", "nike", "xexymix", "nb", "fila"],
    category: "sports",
    tag: ["Sports", "Casual", "Outdoor"],
  },
];

export default BrandList;
